services:
  frontend:
    container_name: app-front
    build:
      context: ./frontend
      dockerfile: docker/prod.Dockerfile 
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - local
    command: npm run dev
  backend:
    container_name: app-back
    build:
      context: ./backend
      dockerfile: docker/prod.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - local
    command: npm run dev

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

networks:
  local:

volumes:
  evolution_store:
  evolution_instances: