import { Router } from 'express';
import agentRoutes from './agent-routes';
import healthRoutes from './health-routes';
import authRoutes from './auth-routes';
import conversationRoutes from './conversation-routes';
import chunkRoutes from './chunk-routes';
import documentRoutes from './document-routes';
import knowledgeRoutes from './knowledge-routes';
import systemRoutes from './system-param-routes';
import followUpRoutes from './follow-up-routes';
import integrationRoutes from './integration-routes';
import facebookRoutes from './facebook-routes';
import messageRoutes from './message-routes';
import userRoutes from './user-routes';
import departmentRoutes from './department-routes';
import leadRoutes from './lead-routes';
import crmColumnRoutes from './crm-column-routes';
import webhookRoutes from './webhook-routes';
import organizationRoutes from './organization-routes';

const router = Router();

router.use('/agents', agentRoutes);
router.use('/health', healthRoutes);
router.use('/conversations', conversationRoutes);
router.use('/auth', authRoutes);
router.use('/chunks', chunkRoutes);
router.use('/documents', documentRoutes);
router.use('/knowledge', knowledgeRoutes);
router.use('/follow-ups', followUpRoutes);
router.use('/system-params', systemRoutes);
router.use('/integrations', integrationRoutes);
router.use('/facebook', facebookRoutes);
router.use('/messages', messageRoutes);
router.use('/users', userRoutes);
router.use('/departments', departmentRoutes);
router.use('/leads', leadRoutes);
router.use('/crm-columns', crmColumnRoutes); 
router.use('/webhooks', webhookRoutes);
router.use('/organizations', organizationRoutes);

export default router;